### ISSUE TITLE
pak: ERROR: Cannot run installation script "postcache" for exp-js

### ISSUE THREAD

**Issue by liuliu7616** [embedthis/pak#54]
I don't know where is the postcache.[
root@localhost blog]# pak install exp-js
      [Info] Search catalog: "pak" for exp-js for version ~*
     [Cache] exp-js 0.3.2
     [Mkdir] /root/.paks/exp-js/embedthis/0.3.2
       [Get] https://github.com/embedthis/exp-js/archive/v0.3.2.tar.gz
   [Extract] Extract to /root/.paks/exp-js/embedthis/0.3.2
pak: ERROR: Cannot run installation script "postcache" for exp-js
Cannot locate the "npm" utility.
[root@localhost blog]#

**Comment by mobrien** [comment]
Install npm.
