### ISSUE TITLE
Pak windows download error

### ISSUE THREAD

**Issue by thanos04** [embedthis/pak#58]
Hello,

Problem downloading pak windows version (binary). Following error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>CC73E7B9E4F1362D</RequestId>
<HostId>
m2wzHFUXVMplGnuN4KlOs8eEzvRfYzgI0PGLdsSu+x9ZkAfG37+KznuZ5PMs5AP/T+kEIWGcPZ8=
</HostId>
</Error>

Same on the mirror also. 

Thanks

**Comment by mobsense** [comment]
Where did you download from?

**Comment by mobsense** [comment]
Thanks - We've updated the binary downloads for 1.0.2.
